### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by oz5581** [Megghy/MultiSCore#1]
Please make an english version as well pls!!

**Comment by Megghy** [comment]
This is no problem, but this plugin has not been tested too much, there may be some bugs. And due to the limitations of Terraria itself some places will be very strange (such as from a smaller world into a larger world will not be able to display the world in full)

**Comment by Megghy** [comment]
I have added the English option to the plugin, you need to change the LanguageFileName to "en_us.json" in the MSCConfig.json in the MultiSCore folder under the tshock folder. My English is not very good, so many of the tips are machine translated, you can change the translation in the file yourself if you like
