### ISSUE TITLE
Crashing Mobile

### ISSUE THREAD

**Issue by Luke1192** [Megghy/MultiSCore#2]
I used this plugin and everytime I tried to execute /msg <server name> it crashed me. I was on mobile but a pc player tried it and it worked just fine. The only other plugins I had was Moneylovers crossplay. Is there a way for you to fix this and make it to where it does not crash mobile clients

**Comment by Luke1192** [comment]
I mean everytime I tried to change servers

**Comment by Megghy** [comment]
Some of the packet structure of the mobile version is not the same as the PC version, and crossplay modifies the data sent based on the version information sent to the player when they join, but this plugin modifies it, so crossplay will not work. I will make this plugin compatible in future versions

**Comment by Luke1192** [comment]
How long til you will make it compatible?

**Comment by Megghy** [comment]
updated

**Comment by Luke1192** [comment]
Can you make a new release? Also does that mean it works with the crossplay plugin or has its own crossplay?

**Comment by Megghy** [comment]
work with crossplay

**Comment by Luke1192** [comment]
Can you make a new release please?

**Comment by Megghy** [comment]
I've already posted it

**Comment by Luke1192** [comment]
Tysm
